# Generated by Django 4.1.7 on 2023-04-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sensor_datecreated_alter_sensor_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sensors',
            field=models.ManyToManyField(blank=True, related_name='equipment_sensors', to='core.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serialNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('O', 'Oil'), ('M', 'Metal')], max_length=1),
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleType', models.CharField(choices=[('O', 'Oil'), ('M', 'Metal')], max_length=1)),
                ('valueType', models.CharField(choices=[('W', 'Water'), ('F', 'Fuel')], max_length=1)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_sample_timeslot', models.PositiveIntegerField(help_text='Hours before next oil sample needed')),
                ('lubrication_replacement', models.PositiveIntegerField(help_text='Hours before next lubrication replacement needed')),
                ('engine_inspection', models.PositiveIntegerField(help_text='Hours before next engine inspection needed')),
                ('maintenance_required', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='core.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.sensor')),
            ],
        ),
    ]
