# Generated by Django 4.1.7 on 2023-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_equipment_name_alter_equipment_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='type',
            new_name='sensor_type',
        ),
        migrations.AlterField(
            model_name='sample',
            name='valueType',
            field=models.CharField(blank=True, choices=[], max_length=1),
        ),
    ]
